### ISSUE TITLE
CP210x device is required

### ISSUE THREAD

**Issue by cezanne** [cezanne/usbip-vstub#1]
There exists [usbip-win issue](https://github.com/cezanne/usbip-win/issues/144) for CP210x device.

[USB capture log](https://github.com/cezanne/usbip-vstub/files/4532844/CP210x.pcap.zip)  is available and work is in progress.

**Comment by pasha-zzz** [comment]
https://www.aliexpress.com/item/32694152202.html

**Comment by cezanne** [comment]
A preliminary version is implemented. 4382fb6eb3fac1ad7ea9215df7559a3f6295ebbf

**Comment by pasha-zzz** [comment]
Precompiled version is needed. I cant build my self binary...

**Comment by cezanne** [comment]
@pasha-zzz : 
> Precompiled version is needed. I cant build my self binary...

Maybe you mean a precompiled vhci driver. Please refer https://github.com/cezanne/usbip-win/issues/144#issuecomment-619857806

**Comment by cezanne** [comment]
This device had been implemented and merged into the master.
